#:schema node_modules/wrangler/config-schema.json
name = "remix-workers-app"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat"]

main = "./dist/index.js"
assets = { directory = "./public" }


[observability]
enabled = true


[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "Game"]