name = "standard-electric"
main = "dist/index.js"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat"]


assets = { directory = "./public" }

[vars]
ACTOR_KIT_HOST = "standard-electric.jonathanrmumm.workers.dev"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "Game"]
