#:schema node_modules/wrangler/config-schema.json
name = "standard-electric"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat"]

main = "./dist/index.js"
assets = { directory = "./public" }

[vars]
ACTOR_KIT_HOST = "standard-electric.jonathanrmumm.workers.dev"

[observability]
enabled = true


[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "Game"]
